
//Tests for User API
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/690a6ac06b502411047185d6

###
GET http://localhost:3000/api/users?where={"_id": "690a6ac06b502411047185d6"}	


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Five",
    "email": "scott@baker.com",
    "pendingTasks": []
}

###
DELETE http://localhost:3000/api/users/6909b6f336c68449d87089c0


###
PUT http://localhost:3000/api/users/690a6ac06b502411047185d6
Content-Type: application/json

{
    "name": "Test Four"
}


//Test for Task API
###
GET http://localhost:3000/api/tasks

###
GET http://localhost:3000/api/tasks/690a2b955aa3ea1fd4d50e87

###
GET http://localhost:3000/api/tasks?where={"_id": "690a2b955aa3ea1fd4d50e87"}	

###
GET http://localhost:3000/api/tasks?skip=5&limit=2

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "name": "Jake Doe",
    "description": "five@gmail.com",
    "deadline": "2024-12-31T23:59:59.999Z",
    "completed": false,
    "assignedUser": "6909b64a36c68449d87089bc",
    "assignedUserName": "John Doe"
}